ddd

diff --git a/.github/workflows/module3_task1.yml b/.github/workflows/module3_task1.yml
--- a/.github/workflows/module3_task1.yml
+++ b/.github/workflows/module3_task1.yml
@@ -1,40 +1,39 @@
-name: module3_task1
+# Define variables
+Publish=hugo
+SHELLCHECK=shellcheck
 
-on:
-  push:
-    branches:
-      - main
-  schedule:
-    - cron: "0 0 * * *"
+build: ## Builds a new website
+	$(Publish)
 
-    - cron: '10 10 * * *'
-jobs:
-  module3_task1:
-    runs-on: ubuntu-18.04
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: lint
-        run: |
-          cd module3_task1/
-          make lint
-      - name: Setup Hugo
-        run: |
-          cd module3_task1/
-          sudo ./setup.sh
-      - name: build
-        run: |
-          cd module3_task1/
-          make build
-      - name: post
-        run: |
-          cd module3_task1/
-          make POST_TITLE="Test Title" POST_NAME="Test-name" post
-      - name: Integration tests
-        run: |
-          cd module3_task1/
-          make integration-tests
-      - name: clean
-        run: |
-          cd module3_task1/
-          make clean
+clean: ## Remove all files from folder dist
+	rm -r dist/*
+
+post: ## Create new post and using the sed command to modify the contents of a file.
+	$(Publish) new posts/$(POST_NAME).md
+	sed -i 's/title: .*/title: "$(POST_TITLE)"/' content/posts/$(POST_NAME).md
+
+lint: ## shellcheck setup
+	$(SHELLCHECK) setup.sh >/dev/null 2>&1 || echo "Lint Failed"
+
+integration-tests: ## server and check the localhost
+	hugo
+	ls dist/
+
+unit-tests: ## Runs different makefile recipes
+	make POST_TITLE='TEST' POST_NAME='this-is-a-test' post
+	make build
+	make clean
+
+validate: ## Tests dir
+	pwd
+
+help: ## Display the list of targets and their usage.
+	cat Makefile | grep '##' | tr -d '##' | head -n -1
+build:
+	hugo --destination dist
+clean:
+	rm -rf ./dist
+post:
+	rm -rf content/posts/$(POST_NAME).md
+	hugo new posts/$(POST_NAME).md
+	sed -i 's/title*/title: "$(POST_TITLE)"/g' content/posts/$(POST_NAME).md
